categories:
  logging:
    description: Log viewing and monitoring tools
    servers:
      us-east-1:
        script: "export ENDPOINT=logs.us-east-1.example.com; echo \"Connecting to US East logs...\"; sleep 1; echo \"Connected to logging system\"; echo \"Region: us-east-1\"; echo \"Endpoint: $ENDPOINT\""
        description: US East Logging
        
      eu-central-1:
        script: "export ENDPOINT=logs.eu-central-1.example.com; echo \"Connecting to EU Central logs...\"; sleep 1; echo \"Connected to logging system\"; echo \"Region: eu-central-1\"; echo \"Endpoint: $ENDPOINT\""
        description: EU Central Logging
        
      ap-southeast-2:
        script: "export ENDPOINT=logs.ap-southeast-2.example.com; echo \"Connecting to Asia Pacific Sydney logs...\"; sleep 1; echo \"Connected to logging system\"; echo \"Region: ap-southeast-2\"; echo \"Endpoint: $ENDPOINT\""
        description: Asia Pacific Sydney Logging
        
      ap-south-1:
        script: "export ENDPOINT=logs.ap-south-1.example.com; echo \"Connecting to Asia Pacific Mumbai logs...\"; sleep 1; echo \"Connected to logging system\"; echo \"Region: ap-south-1\"; echo \"Endpoint: $ENDPOINT\""
        description: Asia Pacific Mumbai Logging
        
  metrics:
    description: Metrics and monitoring dashboards
    servers:
      us-east-1:
        script: "export ENDPOINT=metrics.us-east-1.example.com; echo \"Connecting to US East metrics...\"; sleep 1; echo \"Connected to metrics system\"; echo \"Region: us-east-1\"; echo \"Endpoint: $ENDPOINT\""
        description: US East Metrics
        
      eu-central-1:
        script: "export ENDPOINT=metrics.eu-central-1.example.com; echo \"Connecting to EU Central metrics...\"; sleep 1; echo \"Connected to metrics system\"; echo \"Region: eu-central-1\"; echo \"Endpoint: $ENDPOINT\""
        description: EU Central Metrics
        
      ap-southeast-2:
        script: "export ENDPOINT=metrics.ap-southeast-2.example.com; echo \"Connecting to Asia Pacific Sydney metrics...\"; sleep 1; echo \"Connected to metrics system\"; echo \"Region: ap-southeast-2\"; echo \"Endpoint: $ENDPOINT\""
        description: Asia Pacific Sydney Metrics